#!/usr/bin/env bash
# This bash init script manages the file "manage_my_process" (not necessary the step 'touch' for create a file, use 'echo')
case "$1" in
  start)
    ./manage_my_process &
    echo $! > /var/run/my_process.pid
    echo "manage_my_process started"
    ;;
  stop)
    pkill -f ./manage_my_process
    rm /var/run/my_process.pid
    echo "manage_my_process stopped"
    ;;
  restart)
    pkill -f ./manage_my_process
    rm /var/run/my_process.pid
    ./manage_my_process &
    echo $! > /var/run/my_process.pid
    echo "manage_my_process restarted"
    ;;
  *)
    echo "Usage: manage_my_process {start|stop|restart}"
    ;;
esac
